config/routes.rb
Rails.application.routes.draw do
  root to: 'dashboard#home'
  get '/list_companies', to: 'list_companies#list_companies'
  post '/list_companies', to: 'list_companies#list_companies'
  get '/history', to: 'issues#history'
  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_server'
  get '/401', to: 'errors#access_denied'
  get '/422', to: 'errors#unprocessable'

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations', confirmations: 'users/confirmations' }, path: 'accounts', path_names: { sign_up: 'new' }

  constraints(subdomain: /^(?!www\Z)(\w+)/) do
    get '/companies/search', to: 'companies#search'

    resources :projects do
      member do
        get 'backlog'
        get 'active_sprint'
      end
      resources :sprints
      resources :projects_users
      resources :issues
    end
    resources :sprints do
      resources :issues
      resources :documents, except: %i[edit update]
      member do
        get 'start_sprint_info'
        patch 'start_sprint'
        get 'complete_sprint_info'
        post 'complete_sprint'
        get 'report'
      end
    end

    resources :issues do
      resources :time_logs
      resources :documents, except: %i[edit update]
      collection do
        post 'add_issues_to_sprint'
        get 'fetch_resource_issues', as: 'fetch_resource'
        get 'add_remove_watcher'
      end
    end
    resources :issues do
      resources :time_logs
    end
    resources :dashboard

    resources :users do
    end

    get '/history', to: 'issues#history'
    resources :reports, only: :index do
      collection do
        get 'sprint'
        get 'issues'
      end
    end
  end
end

app/models/time_log.rb
class TimeLog < ApplicationRecord
  sequenceid :issue, :time_logs

  belongs_to :company
  belongs_to :issue
  belongs_to :assignee, class_name: 'User'

  validates :date, presence: true
  validates :logged_time, numericality: { greater_than: 0 }
end

app/controllers/time_logs_controller.rb
class TimeLogsController < ApplicationController
  load_and_authorize_resource :issue, find_by: :sequence_num
  load_and_authorize_resource find_by: :sequence_num, through: :issue

  # GET /time_logs or /time_logs.json
  def index
    @time_logs = @time_logs.paginate(page: params[:page])
    respond_to do |format|
      format.js
      format.html
    end
  end

  # GET /time_logs/1 or /time_logs/1.json
  def show
    respond_to do |format|
      format.js
    end
  end

  # GET /time_logs/new
  def new
    respond_to do |format|
      format.js
    end
  end

  # GET /time_logs/1/edit
  def edit
    respond_to do |format|
      format.js
    end
  end


  # POST /time_logs
  def create

    #@time_log = TimeLog.new(time_log_params)
    @time_log.assignee_id = current_user.id
    #@time_log.issue_id = @issue.id

    respond_to do |format|
      if @time_log.save
        format.js { flash.now[:notice] = t('shared.success.create', resource_label: t('time_logs.label')) }
      else
        format.js do
          flash.now[:error] = @time_log.errors.full_messages
          flash.now[:error] << t('shared.failure.create', resource_label: t('time_logs.label'))
        end
      end
    end
  end

  # PATCH/PUT /time_logs/1 or /time_logs/1.json
  def update
    respond_to do |format|
      if @time_log.update(time_log_params)
        format.js { flash.now[:notice] = t('shared.success.update', resource_label: t('time_logs.timelogs_label')) }
      else
        flash.now[:error] = @time_log.errors.full_messages
        flash.now[:error] << t('shared.failure.create', resource_label: t('time_logs.label'))
      end
    end
  end

  # DELETE /time_logs/1 or /time_logs/1.json
  def destroy
    respond_to do |format|
      if @time_log.destroy
        format.js { flash.now[:notice] = t('shared.success.delete', resource_label: t('time_logs.label')) }
      else
        format.js { flash.now[:notice] = t('shared.failure.delete', resource_label: t('time_logs.label')) }
      end
    end
  end

  private

  def time_log_params
    params.require(:time_log).permit(:name, :date, :logged_time, :work_description)
  end
end

app/views/time_logs/_progress.html.erb
<div class='progress <%=width%>'>
  <div class="progress-bar" role="progressbar" style="width: <%= time_progression_ratio %>%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"><%= time_progression_ratio.round(2).to_s + '%' %></div>
  <% if total_logged_time.to_i > estimated_time.to_i %>
    <div class="progress-bar bg-danger" role="progressbar" style="width: <%= instance.remaining_progression_percentage(time_progression_ratio) %>%" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100"><%= instance.remaining_progression_percentage(time_progression_ratio).round(2).to_s + '%' %></div>
  <% end %>
</div>

app/views/time_logs/_time_logs.html.erb
<div class="container">
  <div class="row d-flex">
    <div class="col-10 justify-content-start">
      <h1>Time Logs</h1>
    </div>
  </div>
  <br/>
  <table class="table table-hover js-datatable" id="users-datatable" data-source="<%= users_path(format: :json) %>">
    <thead class="bg-primary text-light">
      <tr>
        <th>Assignee</th>
        <th>Time Log</th>
        <th>Date</th>
        <th>Description</th>
        <th>Issue</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @time_logs.each do |time_log| %>
        <tr>
          <td><%= time_log.assignee.name %></td>
          <td><%= time_log.logged_time %></td>
          <td><%= time_log.date%></td>
          <td><%= time_log.work_description%></td>
          <td><%= time_log.issue.title%></td>
          <td><%= link_to "", [:edit, time_log.issue, time_log], class: "bi bi-pencil-fill"  %>
            <%= link_to "", [time_log.issue, time_log] ,method: :delete,
                  data: { confirm: t('shared.confirmation') }, class: "bi bi-trash" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= will_paginate @time_logs %>
</div>

app/views/time_logs/_time_logs_datatable_row.html.erb
<tr id="time_log_<%= time_log.sequence_num %>">  
  <td><%= time_log.assignee.name %></td> 
  <td><%= time_log.logged_time %></td> 
  <td class="col-2"><%= time_log&.date.to_formatted_s(:long) %></td> 
  <td><%= time_log.work_description %></td> 
  <td><%= time_log.issue.title %></td> 
  <td>
    <% if can? :edit, TimeLog => issue, timelog: { assignee: current_user } %>
      <%= link_to ' ', [:edit, time_log.issue, time_log], remote: true, class:"bi bi-pencil-fill" %>
    <% elsif can? %i[read create update destroy], Project %>
      <%= link_to ' ', [:edit, time_log.issue, time_log], remote: true, class:"bi bi-pencil-fill" %>
    <% elsif can? :manage, TimeLog  %>
      <%= link_to ' ', [:edit, time_log.issue, time_log], remote: true, class:"bi bi-pencil-fill" %>
    <% end %>
    <% if can? :destroy, TimeLog => issue %>
      <%= link_to "", [time_log.issue, time_log], remote: true ,method: :delete,
      data: { confirm: t('shared.confirmation') }, class: "bi bi-trash" %>
    <% elsif can? %i[read create update destroy], Project %>
      <%= link_to "", [time_log.issue, time_log], remote: true ,method: :delete,
      data: { confirm: t('shared.confirmation') }, class: "bi bi-trash" %>
    <% elsif can? :manage, TimeLog  %>
      <%= link_to "", [time_log.issue, time_log], remote: true ,method: :delete,
      data: { confirm: t('shared.confirmation') }, class: "bi bi-trash" %>
    <% end %>
  </td>
</tr> 

app/views/time_logs/_time_logs_index.html.erb
<% if can? :create, issue => TimeLog %>
  <div class="container mt-3">
    <div class="row d-flex justify-content-end">
      <div class="col-2">
        <% if can? :create, TimeLog => issue %>
          <%= link_to t('shared.create_new_resource', resource_label: t('time_logs.label')), new_issue_time_log_path, remote: true, class:"btn btn-primary w-100 bi bi-plus" %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>
<div class="container mt-3">
  <div class="text-center" id="time_logs_datatable_space"></div>
</div>

app/views/time_logs/_time_logs_table.html.erb
<div class="card my-4 dashboard-card-border shadow-lg">
  <div class="card-body">
    <table class="table table-hover js-datatable" id="time_logs-datatable" data-source="<%= users_path(format: :json) %>">
      <thead class="bg-primary text-light">
        <tr>
          <th><%= t('time_logs.assignee') %></th>
          <th><%= t('time_logs.label') %></th>
          <th class="col-2"><%= t('time_logs.date') %></th>
          <th><%= t('time_logs.description') %></th>
          <th><%= t('issues.issue_label') %></th>
          <th><%= t('shared.actions') %></th>
        </tr>
      </thead>
      <tbody id="time_logs_datatable_body">
        <% time_logs.each do |time_log| %>
          <%= render 'time_logs_datatable_row', time_log: time_log, issue: time_log.issue %>
        <% end %>
      </tbody>
    </table>
    <%= js_paginate time_logs %>
  </div>
</div>

app/views/time_logs/create.html.erb
<%= render 'form', locals: { time_log: @time_log } %>

app/views/time_logs/create.js.erb
<% if @time_log.errors.present? %>
  $('#modal .modal-flash-messages').html("<%= escape_javascript render partial: 'shared/flash_messages', flash: flash %>");
<% else %>
  if ($("#time_logs-datatable").length == 0){
    $("#time_logs_datatable_space").html("<%= escape_javascript render('time_logs_table', time_logs: [@time_log], issue: @issue) %>")
  }
  else{
    $('#time_logs_datatable_body').append("<%= escape_javascript render 'time_logs_datatable_row', time_log: @time_log, issue: @issue%>");
  }
  $('#formCloseBtn').click();

<% end %>

app/views/time_logs/destroy.js.erb
<% if @time_log.errors.blank? %>
  $('#time_log_<%= @time_log.sequence_num %>').remove();
  if ($("#time_log_datatable_body tr").length == 0) {
    $('#time_log_datatable_space').html("<%= escape_javascript (render partial: 'shared/no_resource_present', locals: { record: t('time_logs.label') }) %>");
  }
<% end %>
$('#flash_messages').html("<%= escape_javascript render partial: 'shared/flash_messages', flash: flash %>");

app/views/time_logs/edit.html.erb
<h1>Editing Time Log</h1>

<%= render 'form', time_log: @time_log %>

app/views/time_logs/edit.js.erb
$('#modal').html("<%= escape_javascript render('form', issue: @issue, time_log: @time_log) %>");
$('#modal .modal-header').html("<h1><%= t('shared.edit_resource', resource_label: t('time_logs.label')) %></h1>");
$('#modal').modal('show');

app/views/time_logs/index.html.erb
<div class="container">
  <div class="row d-flex">
    <div class="col-10 justify-content-start">
      <h1>Time Logs</h1>
    </div>
    <% if can? :create, TimeLog %>
      <div class="col-2 justify-content-end">
        <%= link_to "Add New Time Log", new_issue_time_log_path, class: "btn btn-primary w-100 bi bi-plus"  %>
      </div>
    <%end%>
  </div>
  <br/>
  <table class="table table-striped table-bordered table-hover js-datatable" id="users-datatable" data-source="<%= users_path(format: :json) %>">
    <thead class="bg-primary text-light">
      <tr>
        <th>Assignee</th>
        <th>Time Log</th>
        <th>Date</th>
        <th>Description</th>
        <th>Issue</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @time_logs.each do |time_log| %>
        <tr>
          <td><%= time_log.assignee.name %></td>
          <td><%= time_log.logged_time %></td>
          <td><%= time_log.date%></td>
          <td><%= time_log.work_description%></td>
          <td><%= time_log.issue.title%></td>
          <td><%= link_to "", [:edit, time_log.issue, time_log], class: "bi bi-pencil-fill"  %>
            <%= link_to "", [time_log.issue, time_log] ,method: :delete,
                data: { confirm: t('shared.confirmation') }, class: "bi bi-trash" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= will_paginate @time_logs %>
</div>

app/views/time_logs/index.js.erb
$('#nav-time_logs').html("<%= escape_javascript render('time_logs_index', time_logs: @time_logs, issue: @issue) %>");
<% if @time_logs.present? %>
  $('#time_logs_datatable_space').html("<%= escape_javascript render('time_logs_table', issue: @issue, time_logs: @time_logs) %>");
<% else %>
  $('#time_logs_datatable_space').html("<%= escape_javascript (render partial: 'shared/no_resource_present', locals: { record: t('time_logs.label') }) %>");
<% end %>

app/views/time_logs/show.html.erb
<div class="container mt-3">
  <div class="row bm-3 d-flex">
    <div class="col-8">
      <h1><%= @user.name %></h1>
    </div>
    <% if can? :edit, @user %>
    <div class="col-2 justify-content-end">
      <%= link_to t('shared.edit'), edit_user_path(@user), class: "btn btn-primary w-100 fa fa-pencil" %>
    </div>
    <% end %>
    <% if can? :destroy, @user %>
      <div class="col-2 justify-content-end">
        <%= link_to t('shared.destroy'), user_path(@user),method: :delete,
                data: { confirm: t('shared.confirmation') }, class: "btn btn-danger w-100 fa fa-trash" %>
      </div>
    <% end %>
  </div>
  <hr/>
</div>
<div class="container">
  <div class="row bm-3">
    <div class="col-3 ">
      <p><strong><%=t('users.name')%>:</strong></p>
    </div>
    <div class="col-3">
      <p><%=@user.name %></p>
    </div>
    <div class="col-3 ">
      <p><strong><%=t('users.email')%>:</strong></p>
    </div>
    <div class="col-3">
      <p><%= @user.email %></p>
    </div>
    <div class="col-3">
      <p><%= @user.role_id == 1? "Admin" : "Member"%></p>
    </div>
  </div>
  <hr/>
</div>

app/views/time_logs/update.js.erb
<% if @time_log.errors.any? %>
  $('#modal .modal-flash-messages').prepend("<%= escape_javascript render partial: 'shared/flash_messages', flash: flash %>");
<% else %>
  $('#flash_messages').html("<%= escape_javascript render partial: 'shared/flash_messages', flash: flash %>");
  $('#time_log_<%= @time_log.sequence_num %>').replaceWith("<%= escape_javascript render 'time_logs_datatable_row', time_log: @time_log %>");
  $('#formCloseBtn').click();
<% end %>