config/routes.rb
Rails.application.routes.draw do
  root to: 'dashboard#home'
  get '/list_companies', to: 'list_companies#list_companies'
  post '/list_companies', to: 'list_companies#list_companies'
  get '/history', to: 'issues#history'
  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_server'
  get '/401', to: 'errors#access_denied'
  get '/422', to: 'errors#unprocessable'

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations', confirmations: 'users/confirmations' }, path: 'accounts', path_names: { sign_up: 'new' }

  constraints(subdomain: /^(?!www\Z)(\w+)/) do
    get '/companies/search', to: 'companies#search'

    resources :projects do
      member do
        get 'backlog'
        get 'active_sprint'
      end
      resources :sprints
      resources :projects_users
      resources :issues
    end
    resources :sprints do
      resources :issues
      resources :documents, except: %i[edit update]
      member do
        get 'start_sprint_info'
        patch 'start_sprint'
        get 'complete_sprint_info'
        post 'complete_sprint'
        get 'report'
      end
    end

    resources :issues do
      resources :time_logs
      resources :documents, except: %i[edit update]
      collection do
        post 'add_issues_to_sprint'
        get 'fetch_resource_issues', as: 'fetch_resource'
        get 'add_remove_watcher'
      end
    end
    resources :issues do
      resources :time_logs
    end
    resources :dashboard

    resources :users do
    end

    get '/history', to: 'issues#history'
    resources :reports, only: :index do
      collection do
        get 'sprint'
        get 'issues'
      end
    end
  end
end

app/models/issue.rb
# frozen_string_literal: true

class Issue < ApplicationRecord
  searchkick word_middle: %i[titile description], filterable: %i[company_id]

  include DateValidations
  include TimeProgressions

  STATUS = { open: 'Open', in_progress: 'In Progress', resolved: 'Resolved', closed: 'Closed' }.freeze
  PRIORITY = { low: 'Low', medium: 'Medium', high: 'High' }.freeze
  CATEGORY = { hotfix: 'Hotfix', feature: :Feature }.freeze
  FILTER = { Assignee: 'assignee', Creator: 'creator', Project: 'project', Status: 'status', Category: 'category', Priority: 'priority', Reviewer: 'reviewer' }.freeze

  after_save :issue_alerts

  belongs_to :company
  belongs_to :project
  belongs_to :sprint, optional: true
  belongs_to :creator, class_name: 'User'
  belongs_to :assignee, class_name: 'User', optional: true
  belongs_to :reviewer, class_name: 'User', optional: true
  has_many :time_logs, dependent: :destroy
  has_many :watchers
  has_many :watching_users, source: :user, through: :watchers
  has_many :documents, as: :attachable, dependent: :destroy

  sequenceid :company, :issues
  validates :title, length: { minimum: 4, maximum: 255 }
  validates :description, length: { minimum: 6, maximum: 5000 }
  validates :title, :description, :status, :priority, presence: true
  audited associated_with: :company

  validate_datetime :actual_end_date
  validate_datetime :actual_start_date
  validate_datetime :estimated_end_date
  validate_datetime :estimated_start_date

  validates :estimated_time, length: { maximum: 100 }, numericality: { greater_than: 0, allow_blank: true}
  validate_dates :estimated_start_date, :estimated_end_date
  validate_dates :actual_start_date, :actual_end_date

  scope :creator, ->(creator) { where creator: creator }
  scope :filter_by_attribute, ->(column, value) { where column => value }
  scope :open, -> { where(status: STATUS.key('Open')) }
  scope :closed, -> { where(status: STATUS.key('Closed')) }
  scope :resolved, -> { where(status: STATUS.key('Resolved')) }
  scope :in_progress, -> { where(status: STATUS.key('In Progress')) }
  scope :high_priority, -> { where(priority: PRIORITY[:high]) }
  sequenceid :company, :issues
  audited associated_with: :company

  after_save :issue_alerts


  def total_time_spent
    time_logs&.sum(:logged_time) || 0
  end

  def assignee_name
    assignee&.name || I18n.t('issues.no_assignee')
  end

  def total_estimated_time
    estimated_time || 0
  end

  def self.get_errors_of_collection(issues)
    errors = []
    issues.each do |issue|
      errors.concat(issue.errors.full_messages)
    end
    errors
  end

  def self.users_name(ids)
    user_name = []
    user_name[0] = User.find_by(id: ids[0].to_i)&.name || I18n.t('shared.no_resource_found', resource_label: 'user')
    user_name[1] = User.find_by(id: ids[1].to_i)&.name || I18n.t('shared.no_resource_found', resource_label: 'user')
    user_name
  end

  def self.issues_left_unresolved_ideally(sprint, date)
    sprint.sprint_report_issues.where("estimated_end_date > ?", date).or(sprint.issues.where(estimated_end_date: nil)).where.not(status: STATUS.key('Closed')).size
  end

  def self.issues_left_unresolved_actually(sprint, date)
    sprint.sprint_report_issues.where("actual_end_date > ?", date).or(sprint.issues.where(actual_end_date: nil)).where.not(status: STATUS.key('Closed')).size
  end

  private

  def issue_alerts
    return if previous_changes.empty?

    watcher = watchers.pluck(:user_id)
    alert_receivers = [reviewer_id, assignee_id, creator_id, project.manager_id]
    alert_receivers.concat watcher

    users = company.users.where(id: alert_receivers).or(company.users.where(role_id: User::ROLE_ID[:admin]))

    subject = I18n.t('issues.email_subject')

    users.each do |user|
      UserMailer.delay.issue_alerts(user, self, Company.current_company.subdomain, Current.user, subject, previous_changes)
    end
  end
end

app/controllers/issues/comments_controller.rb
class Issues::CommentsController < CommentsController
  before_action :set_commentable

  private
  def set_commentable
    @commentable = Issue.find_by(id: params[:issue_id])
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  load_and_authorize_resource :project, find_by: :sequence_num, through: :current_company, if: -> { params[:project_id].present? }
  load_and_authorize_resource :issue, find_by: :sequence_num, through: :project, if: -> { params[:project_id].present? }
  load_and_authorize_resource :sprint, find_by: :sequence_num, if: -> { params[:sprint_id].present? }
  load_and_authorize_resource :issue, find_by: :sequence_num, through: :sprint, if: -> { params[:sprint_id].present? }
  load_and_authorize_resource :issue, find_by: :sequence_num, through: :current_company, if: -> { params[:project_id].blank? }

  before_action :set_creator, only: :create

  before_action :add_breadcrumbs, only: [:index, :show]
  before_action :fetch_required_data, only: [:new, :edit, :index, :fetch_resource_issues]

  # GET /issues
  def index
    @issues = @issues.includes(:creator, :reviewer, :project, :assignee).paginate(page: params[:page])
    @issues = FilteringParams.new(@issues, params).apply_filters
    respond_to do |format|
      format.js
      format.html
    end
  end

  def history
    @issue = @issues.find_by(sequence_num: params[:issue])
    respond_to do |format|
      format.js
    end
  end

  # GET /issues/:sequence_num
  def show
    add_breadcrumb @issue.title.titleize, issue_path
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /issues/new
  def new
    respond_to do |format|
      format.js
    end
  end

  # GET issues/:sequence_num/edit
  def edit
    respond_to do |format|
      format.js
      format.html
    end
  end

  # POST /issues/
  def create
    respond_to do |format|
      if @issue.save
        flash.now[:notice] = t('shared.success.create', resource_label: t('issues.issue_label'))
      else
        flash.now[:error] = @issue.errors.full_messages
      end
      format.js
    end
  end

  # PUT /issues/:sequence_num/edit
  def update
    respond_to do |format|
      if @issue.update(issue_params)
        flash.now[:notice] = t('shared.success.update', resource_label: t('issues.issue_label'))
      else
        flash.now[:error] = @issue.errors.full_messages
      end
      format.js
    end
  end

  # DELETE /issues/:sequence_num
  def destroy
    respond_to do |format|
      if @issue.destroy
        format.js { flash.now[:notice] = t('shared.success.delete', resource_label: t('issues.issue_label')) }
        format.html { redirect_to issues_url }
      else
        flash.now[:error] = t('shared.failure.delete', resource_label: t('issues.issue_label'))
        format.js
        format.html { render :show }
      end
    end
  end


  def fetch_resource_issues
    if params[:assignee_id].present?
      @issues = @current_company.issues.accessible_by(current_ability).where(assignee_id: current_user.id)
    elsif params[:creator_id].present?
      @issues = @current_company.issues.accessible_by(current_ability).where(creator_id: current_user.id)
    elsif params[:reviewer_id].present?
      @issues = @current_company.issues.accessible_by(current_ability).where(reviewer_id: current_user.id)
    else
      @issues = @current_company.issues.accessible_by(current_ability).where(assignee_id: current_user.id)
    end
    @issues = @issues.paginate(page: params[:page])
    respond_to do |format|
      format.js
    end
  end

  def add_remove_watcher
    @issue = @current_company.issues.find_by(id: params.dig(:issue_id))
    success = false
    if @issue.nil?
      flash.now[:error] = t('issues.issue_label') + t('issues.not_found')
    else
      watcher = @current_company.watchers.where(issue: @issue).find_by(user_id: current_user.id)
      create_true = watcher.blank?
      if create_true
        success = Watcher.create!(user: current_user, issue: @issue)
      else
        success = watcher.destroy
      end

      if create_true
        if success
          flash.now[:notice] = t('issues.watcher_added_success')
        else
          flash.now[:error] = watcher.errors.full_messages
        end
      else
        if success
          flash.now[:notice] = t('issues.watcher_removed_success')
        else
          flash.now[:error] = watcher.errors.full_messages
        end
      end

      respond_to do |format|
        format.js
      end
    end
  end

  # POST issues/add_issues
  def add_issues_to_sprint
    issue_ids = params[:issue_ids].split(',')
    @issues = Issue.where(id: issue_ids)
    @sprint = Sprint.find_by(sequence_num: params[:sprint_id])

    respond_to do |format|
      if @sprint.errors.blank? && @issues.update(sprint: @sprint)
        format.js { flash.now[:notice] = t('issues.issues_added_success') }
      else
        @errors = Issue.get_errors_of_collection(@issues)
        @errors.concat @sprint.errors.full_messages
        format.js { flash.now[:error] = @errors }
      end
    end
  end

  private

  # Only allow a list of trusted parameters through.
  def issue_params
    params.require(:issue).permit(:title, :description, :status, :category, :estimated_time, :priority, :estimated_end_date,
                                  :estimated_start_date, :actual_start_date, :actual_end_date, :reviewer_id, :creator_id, :assignee_id, :project_id)
  end

  def set_creator
    @issue.creator = current_user
  end

  def fetch_required_data
    @projects = @current_company.projects
    @users = @current_company.users
  end

  def add_breadcrumbs
    add_breadcrumb t('issues.issue_label').pluralize, issues_path
  end
end

app/helpers/issues_helper.rb
# app/helpers/issues_helper

module IssuesHelper
  def get_status_color(status)
    status_color = { open: 'primary', in_progress: 'warning', resolved: 'info', closed: 'success' }
    status_color[status.to_sym]
  end

  def get_priority_color(priority)
    priority_color = { low: 'success', medium: 'warning', high: 'danger' }
    priority_color[priority.to_sym]
  end

  def get_category_color(category)
    category_color = { hotfix: 'danger', feature: 'success' }
    category_color[category.to_sym]
  end

  def filter_select(form, params)
    if params[:project_id].present?
      filters = Issue::FILTER.except(:Project)
    else
      filters = Issue::FILTER
    end
    form.select t('filter.filter_label'), filters, { include_blank: true }, { class: 'js-select-field js-filter-field form-select form-select-lg' }
  end

  def convert_to_date(date)
    date&.to_date&.to_s(:long)
  end
end

app/views/issues/_dashboard_issue_table.html.erb
<div class="container mb-3">
  <div class="mt-5">
    <div class="card shadow-lg dashboard-card-border">
      <div class="card-body">
        <div>
          <%= pie_chart issues.group(:status).count, colors: [ '#e34','#17f','#285','#1df' ], id: chart_id %>
        </div>
      </div>
    </div>
  </div>
  <div class="card mt-4 dashboard-card-border shadow-lg">
    <div class="card-body">
      <table class="table table-hover border-primary text-center js-datatable" id="issues_datatable">
        <thead class="text-light bg-primary">
          <tr>
            <th><%= t('issues.status') %></th>
            <th><%= t('issues.title') %></th>
            <th><%= t('issues.assignee') %></th>
            <th><%= t('issues.priority') %></th>
            <th><%= t('issues.category') %></th>
            <th><%= t('shared.actions') %></th>
          </tr>
        </thead>
        <tbody id="issues_datatable_body">
          <% if issues.empty? %>
            <div class="container text-center">
              <tr id="no-resource">
                <td colspan="5"><%= render partial: 'shared/no_resource_present', locals: { record: t('issues.issue_label') } %></td>
              </tr>
            </div>
          <% else %>
            <% issues.each do |issue| %>
              <%= render 'issues/issue_datatable_row', issue:issue %>
            <% end %>
          <% end %>
        </tbody>
      </table>
      <%= js_paginate issues %>
    </div>
  </div>
</div>

app/views/issues/_filter.html.erb
<div class="container mb-3">
  <%= form_with  local: false, action: form_action, method: :get do |form| %>
    <div class="row d-flex justify-content-end me-1">
      <div class="col-3 col-sm-3 col-md-2 col-lg-1 control-label"><%= form.label t('filter.filter_label'), class: 'col-form-label col-form-label-md'  %>
      </div>
      <div class="col-9 col-md-4 col-lg-2">
        <%= filter_select(form, params) %>
      </div>
    </div>
    <div class="row collapse", id="creator" >
      <div class="col-12 col-sm-4 col-md-4 col-lg-1  justify-content-start control-label">
        <%= form.label t('issues.creator'), class: 'col-form-label col-form-label-md' %>
      </div>
      <div class="col-12 col-sm-8 col-md-6 col-lg-2" ,id="js-creator">
        <%= form.select :creator, users.map{ |user| [user.name, user.id] } , {}, { disabled: true, class: "js-select-field js-creator-field form-select form-select-lg" }  %>
      </div>
      <div class="col-1">
        <%= link_to '', '#_', class: 'btn btn-close js-remove-filter'  %>
      </div>
    </div>
    <div class="row collapse", id="reviewer">
      <div class="col-12 col-sm-4 col-md-4 col-lg-1  justify-content-start control-label">
        <%= form.label t('issues.reviewer'), class: 'col-form-label col-form-label-md' %>
      </div>
      <div class="col-12 col-sm-8 col-md-6 col-lg-2">
        <%= form.select :reviewer, users.map{|user| [user.name, user.id] } ,{}, { disabled: true, class: "js-select-field form-select js-reviewer-field form-select-lg" }  %>
      </div>
      <div class="col-1">
        <%= link_to '', '#_', class: 'btn btn-close js-remove-filter'   %>
      </div>
    </div>
    <div class="row col-12 no-gutters collapse", id="assignee">
      <div class="col-12 col-sm-4 col-md-4 col-lg-1  justify-content-start control-label">
        <%= form.label t('issues.assignee'), class: 'col-form-label col-form-label-md' %>
      </div>
      <div class="col-12 col-sm-8 col-md-6 col-lg-2">
        <%= form.select :assignee, users.map{ |user| [user.name, user.id] } ,{}, { disabled: true, class: "js-select-field js-assignee-field form-select  form-select-lg"}  %>
      </div>
      <div class="col-1">
        <%= link_to '', '#_', class: 'btn btn-close js-remove-filter'  %>
      </div>
    </div>
    <div class="row  collapse", id="project">
      <div class="col-12 col-sm-4 col-md-4 col-lg-1  justify-content-start control-label">
        <%= form.label t('projects.project_label'), class: 'col-form-label col-form-label-md' %>
      </div>
      <div class="col-12 col-sm-8 col-md-6 col-lg-2", id="js-project">
        <%= form.select :project, projects.map{|project| [project.name, project.sequence_num] }, {}, { disabled: true, class: "js-select-field js-project-field form-select form-select-lg" }%>
      </div>
      <div class="col-1">
        <%= link_to '','#_', class: 'btn btn-close js-remove-filter' %>
      </div>
    </div>
    <div class="row  collapse", id="status">
      <div class="col-12 col-sm-4 col-md-4 col-lg-1  justify-content-start control-label">
        <%= form.label t('issues.status'), class: 'col-form-label col-form-label-md' %>
      </div>
      <div class="col-12 col-sm-8 col-md-6 col-lg-2", id="js-status">
        <%= form.select :status, Issue::STATUS.invert, { }, {disabled: true, class: "js-select-field js-status-field form-select form-select-lg js-status-field"} %>
      </div>
      <div class="col-1">
        <%= link_to '', '#_', class: 'btn btn-close js-remove-filter' %>
      </div>
    </div>
    <div class="row  collapse", id="priority">
      <div class="col-12 col-sm-4 col-md-4 col-lg-1  justify-content-start control-label">
        <%= form.label t('issues.priority'), class: 'col-form-label col-form-label-md' %>
      </div>
      <div class="col-12 col-sm-8 col-md-6 col-lg-2">
        <%= form.select :priority, Issue::PRIORITY.invert, {}, {disabled: true, class: 'js-select-field  form-select form-select-lg4  js-priority-field'}%>
      </div>
      <div class="col-1">
        <%= link_to '', '#_', class: 'btn btn-close js-remove-filter'  %>
      </div>
    </div>
    <div class="row collapse", id="category">
      <div class="col-12 col-sm-4 col-md-4 col-lg-1  justify-content-start control-label">
        <%= form.label t('issues.category'), class: 'col-form-label col-form-label-md'  %>
      </div>
      <div class="col-12 col-sm-8 col-md-6 col-lg-2">
        <%= form.select :category, Issue::CATEGORY.invert, {}, {disabled: true, class: "js-select-field form-select form-select-lg  js-category-field"}%>
      </div>
      <div class="col-1">
        <%= link_to '', '#_', class: 'btn btn-close js-remove-filter'  %>
      </div>
    </div>
    <div class="col-1 btn-apply-filter collapse">
      <%= form.submit 'Apply', class: 'btn btn btn-outline-primary mt-4 px-4', remote: true %>
    </div>
    <div class="col-1 btn-remove-filter collapse">
      <%= form.submit 'Remove Filter', class: 'btn btn btn-outline-primary mt-4 px-4', remote: true %>
    </div>
  <% end %>
</div>

app/views/issues/_history.html.erb
<div class="container">
  <br/><br/>
  <% issue.audits.includes(:user).decorate.drop(1).each do |audit| %>
    <%= link_to audit.user&.name, user_path(audit.user&.sequence_num) %> 
    <%= distance_of_time_in_words(audit.created_at, Time.zone.now) %> ago
    <hr class="mt-1"/>
    <ul>
      <% audit[:audited_changes].each do |attribute, value| %>
        <li> 
          <b><%= attribute.titleize %></b>
          updated from <I><%= audit.previous_value(attribute, value[0]) %></I> to <I><%= audit.new_value(attribute, value[1]) %></I>
        </li>
      <% end %>
    </ul>
  <% end %>
  <div class="d-flex justify-content-left lead"><%= t('issues.no_histoires') if issue.audits.size == 1  %></div>
</div>

app/views/issues/_issue_datatable_row.html.erb
<tr id="issue_<%= issue.sequence_num %>">
  <div id="issues_datatable_space"></div>
  <% if issue.assignee.present? %>
    <% assignee_name = link_to issue.assignee_name, user_path(issue.assignee.sequence_num) %>
  <% end %>
  <td><span class="badge rounded-pill bg-<%= get_status_color(issue.status) %>">
      <%= issue.status.camelize %></span></td>
  <td><%= link_to issue.title, issue_path(issue) %></td>
  <td><%= assignee_name %> </td>
  <td><span class="badge rounded-pill bg-<%= get_priority_color(issue.priority) %>">
      <%= issue.priority.camelize %></span></td>
  <td><span class="badge rounded-pill bg-<%= get_category_color(issue.category) %>">
      <%= issue.category.camelize %></span></td>
  <td>
    <% if can? :edit, Issue %>
      <%= link_to '', edit_issue_path(issue), { :remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', class: 'bi bi-pencil' } %>
    <% end %>
    <% if can? :destroy, Issue %>
      <%= link_to '', issue_path(issue), remote: true , method: :delete, data: {confirm: t('shared.confirmation') }, class: "bi bi-trash" %>
    <% end %>
  </td>
</tr>

app/views/issues/add_watcher.js.erb
<% if @errors.present? %>
  $('#modal .modal-flash-messages').prepend("<%= escape_javascript render partial: 'shared/flash_messages', flash: flash %>");
<% else %>
  $('#flash_messages').html("<%= escape_javascript render partial: 'shared/flash_messages', flash: flash %>");
<% end %>

app/views/issues/create.js.erb
<% if @issue.errors.present? %>
  $('#modal .modal-flash-messages').html("<%= escape_javascript render partial: 'shared/flash_messages' %>");
<% else %>
  $('#flash_messages').html("<%= escape_javascript render partial: 'shared/flash_messages' %>");
  $('#no-resource').remove();
  $('#issues_datatable_body').append("<%= escape_javascript render 'issue_datatable_row', issue: @issue %>");
  $('#formCloseBtn').click();
<% end %>
  

app/views/issues/destroy.js.erb
<% if @issue.errors.blank? %>
  $('#issue_<%= @issue.sequence_num %>').remove();
  if ($("#issues_datatable_body tr").length == 0) {
    $('#issues_datatable_space').html("<%= escape_javascript (render partial: 'shared/no_resource_present', locals: { record: t('issues.issue_label') }) %>");
  }
<% end %>
$('#flash_messages').html("<%= escape_javascript render partial: 'shared/flash_messages', flash: flash %>");

app/views/issues/edit.html.erb
<div class="card-header">
	<h3 class="text-center font-weight-light my-4"><%= t('shared.edit_resource', resource_label: t('issues.issue_label')) %></h3>
</div>
<p/>
<div class="container">
	<%= render 'form', issue: @issue, project: @issue.project, projects: @projects %>
</div>

app/views/issues/fetch_resource_issues.js.erb
<% if params[:assignee_id].present? %>
$('#nav-assignee').html("<%= escape_javascript render(:partial => 'issues/dashboard_issue_table',  :locals=>{ issues: @issues, chart_id: 'assignee_issues'} ) %>");
<% elsif params[:creator_id].present? %>
$('#nav-creator').html("<%= escape_javascript render(:partial => 'issues/dashboard_issue_table',  :locals=>{ issues: @issues , chart_id: 'creator_issues'} ) %>");
<% elsif params[:reviewer_id].present? %>
$('#nav-reviewer').html("<%= escape_javascript render(:partial => 'issues/dashboard_issue_table',  :locals=>{ issues: @issues, chart_id: 'reviewer_issues'} ) %>");
<% else %>
$('#nav-assignee').html("<%= escape_javascript render(:partial => 'issues/dashboard_issue_table',  :locals=>{ issues: @issues , chart_id: 'assignee_issues'} ) %>");
<% end %>

app/views/issues/index.js.erb
<% if (Issue::FILTER.values & params.keys).empty? %>
  $('#header').html("<%= escape_javascript render(:partial => 'issues/header',  :locals=>{projects: @projects,project:@project, issue: @issue} ) %>");
  $('#filter').html("<%= escape_javascript render(:partial => 'issues/filter',  :locals=>{issues: @issues, users: @users, projects: @projects, form_action: "index" } ) %>");
  var data = $('form').serialize();
  if (data.match(/&/g).length < 2)
  {
    $('.btn-remove-filter').hide();
  }
<% end %>

$('#issues-table').html("<%= escape_javascript render(:partial => 'issues/table',  :locals=>{ issues: @issues} ) %>");
$('.js-select-field').select2({
  width: 200
});

 $('body').on('select2:open', '.js-filter-field', () => {
    document.querySelector('.select2-search__field').focus();
  });

$('body').on('select2:open', '.js-select-field', () => {
  document.querySelector('.select2-search__field').focus();
});

$(document).on('select2:select', ".js-filter-field", function(e) {
  var select_container_id = e.params.data["id"];
  $('.btn-apply-filter').show();
  $("#" + select_container_id).addClass('show');
  $(".js-" + select_container_id + "-field").prop("disabled", false);
  $('.btn-apply-filter').show();
  $('.btn-remove-filter').hide();
});

$('.js-remove-filter').on('click', function(e){
  e.preventDefault();
  var parent = this.parentNode.parentNode.id;
  var id ="#"+parent
  var className = ".js-"+parent+"-field"
  $(id).removeClass('show');
  $(className).prop( "disabled", true );
  var data = $('form').serialize();
  if (data.match(/&/g).length < 2)
  {
    $('.btn-apply-filter').hide();
    $('.btn-remove-filter').show();
  }
});

app/views/issues/new.js.erb
$("#modal").html("<%= escape_javascript render('form', project: @project, issue: @issue, projects: @projects, users: @users )%>");
$("#modal").modal('show');

var dateFunc = function() {
  $(".js-flatpickr-date").flatpickr({
    enableTime: false
  });
}
dateFunc();

<% if @project.nil?  %>
  $('#issue_project_id').val(null);
<% end %>

app/views/issues/show.html.erb
<%= render partial: 'shared/breadcrumb' %>
<%= render partial: "issues/show_header", locals: { issue: @issue } %>
<div class="container">
  <ul class="nav nav-tabs bg-gray" id="issue" role="tablist">
    <li class="nav-item active" role="presentation">
      <%= link_to t('issues.issue_label'), issue_path, remote: true, class: 'nav-link active', id: "nav-issues-tab", data: {bs_toggle: "tab", bs_target: "#nav-issues"}, type: "button", role: 'tab', aria_controls: "nav-issues",aria_selected: true  %>
    </li>
    <% if can? :history, Issue%>
      <li class="nav-item" role="presentation">
        <%= link_to t('issues.history_label'), history_path(issue: @issue), remote: true, class: 'nav-link', id: "nav-history-tab", data: {bs_toggle: "tab", bs_target: "#nav-history"}, type: "button", role: 'tab', aria_controls: "nav-history" ,aria_selected: true %>
      </li>
    <% end %>
    <li class="nav-item" role="presentation">
      <%= link_to t('time_logs.label').pluralize(), [@issue, :time_logs], remote: true, class: 'nav-link', id: "nav-time_logs-tab", data: { bs_toggle: "tab", bs_target: "#nav-time_logs" }, type: "button", role: 'tab', aria_controls: "nav-time_logs", aria_selected: false %>
    </li>
    <li class="nav-item" role="presentation">
      <%= link_to t('documents.label').pluralize(), issue_documents_url(@issue), remote: true, class: 'nav-link', id: "nav-documents-tab", data: {bs_toggle: "tab", bs_target: "#nav_documents"}, type: "button", role: 'tab', aria_controls: "nav-documents", aria_selected: false %>
    </li>
  </ul>
  <div class="tab-content" id="issue_content">
    <div class="tab-pane fade show active" id="nav-issues" role="tabpanel" aria-labelledby="nav-issues-tab">
      <%= render partial: "show", locals: { issue: @issue } %>
    </div>
    <% if can? :history, Issue%>
      <div class="tab-pane fade" id="nav-history" role="tabpanel" aria-labelledby="nav-history-tab">
        <div id="history"></div>
      </div>
    <% end %>
    <div class="tab-pane fade" id="nav-time_logs" role="tabpanel" aria-labelledby="nav-time_logs-tab"></div>
    <div class="tab-pane fade" id="nav_documents" role="tabpanel" aria-labelledby="nav-documents-tab"></div>
  </div>
</div>

app/views/issues/show.js.erb
$("#nav-issues").html("<%= escape_javascript render(:partial => 'issues/show',  :locals=>{ issue: @issue} ) %>");