config/routes.rb
Rails.application.routes.draw do
  root to: 'dashboard#home'
  get '/list_companies', to: 'list_companies#list_companies'
  post '/list_companies', to: 'list_companies#list_companies'
  get '/history', to: 'issues#history'
  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_server'
  get '/401', to: 'errors#access_denied'
  get '/422', to: 'errors#unprocessable'

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations', confirmations: 'users/confirmations' }, path: 'accounts', path_names: { sign_up: 'new' }

  constraints(subdomain: /^(?!www\Z)(\w+)/) do
    get '/companies/search', to: 'companies#search'

    resources :projects do
      member do
        get 'backlog'
        get 'active_sprint'
      end
      resources :sprints
      resources :projects_users
      resources :issues
    end
    resources :sprints do
      resources :issues
      resources :documents, except: %i[edit update]
      member do
        get 'start_sprint_info'
        patch 'start_sprint'
        get 'complete_sprint_info'
        post 'complete_sprint'
        get 'report'
      end
    end

    resources :issues do
      resources :time_logs
      resources :documents, except: %i[edit update]
      collection do
        post 'add_issues_to_sprint'
        get 'fetch_resource_issues', as: 'fetch_resource'
        get 'add_remove_watcher'
      end
    end
    resources :issues do
      resources :time_logs
    end
    resources :dashboard

    resources :users do
    end

    get '/history', to: 'issues#history'
    resources :reports, only: :index do
      collection do
        get 'sprint'
        get 'issues'
      end
    end
  end
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :attachable, polymorphic: true
  has_attached_file :file

  # validates_format_of :attachment_file_name, with: /\.(docx|doc|pdf)/
  validates :file, :attachable, presence: true
  validates_attachment_content_type :file, content_type: ['application/pdf', 'application/doc', 'application/docx',
                                                          'image/jpeg', 'image/gif', 'image/png', 'image/jpg', 'image/bmp']
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  load_and_authorize_resource :sprint, find_by: :sequence_num, instance_name: :attachable, if: -> { params[:sprint_id].present? }
  load_and_authorize_resource :issue, find_by: :sequence_num, instance_name: :attachable, if: -> { params[:issue_id].present? }
  load_and_authorize_resource :document, through: :attachable

  def index
    respond_to do |format|
      format.js
    end
  end

  def new
    respond_to do |format|
      format.js
    end
  end

  def create
    respond_to do |format|
      if @document.save
        format.js { flash.now[:notice] = t('shared.success.add', resource_label: t('documents.label')) }
      else
        format.js { flash.now[:error] = @document.errors.full_messages }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @document.destroy
        format.js { flash.now[:notice] = t('shared.success.delete', resource_label: t('documents.label')) }
      else
        format.js { flash.now[:error] = @document.errors.full_messages }
      end
    end
  end

  private

  def document_params
    params.require(:document).permit(:file)
  end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_documents.html.erb
<% new_document_path = params[:sprint_id].nil? ? new_issue_document_url(attachable) : new_sprint_document_url(attachable)  %>
<div class="container mt-3">
  <div class="d-flex justify-content-end">
    <%= link_to t('shared.create_new_resource', resource_label: t('documents.label')), new_document_path, remote: true, class:"btn btn-primary bi bi-plus" %>
  </div>
  <% if documents.blank? %>
    <%= render partial: 'shared/no_resource_present', locals: { record: t('documents.label').pluralize } %>
  <% else %>
    <div class="card mt-4 dashboard-card-border shadow-lg">
      <div class="card-body">
        <table class="table table-hover border-primary text-center js-datatable my-3" id="inactive-sprints">
          <thead class="bg-primary text-light">
            <tr>
              <th><%= t('documents.name') %></th>
              <th><%= t('documents.type') %></th>
              <th><%= t('shared.actions') %></th>
            </tr>
          </thead>
          <tbody>
            <% documents.each do |document| %>
              <tr>
                <td><%= link_to document.file_file_name, document.file.url %></td>
                <td><%= document.file.content_type %></td>
                <td>
                  <%= link_to '', document.file.url, class: 'bi bi-download mx-1' %>
                  <% if can? :destroy, document %>
                    <%= link_to "", [attachable, document], method: :delete, remote: true, data: { confirm: t('shared.confirmation') }, class: "bi bi-trash mx-1" %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  <% end %>
</div>

app/views/documents/_form.html.erb
<div class="modal-dialog modal-lg">
  <div class="modal-content">
    <div class="modal-header"></div>
    <div class="modal-flash-messages"></div>
    <%= form_with model: [@attachable, @document], local: false do |form| %>
      <div class="modal-body">
        <div class="row mb-3">
          <div class="col-4 asterick">
            <%= form.label t('documents.choose_file').upcase, class: "control-label" %>
          </div>
          <div class="col-8 asterick">
            <%= form.file_field :file, class: 'form-control form-control-md' %>
          </div>
        </div>
        <div class="modal-footer">
          <%= form.submit t('shared.create_new_resource', resource_label: t('documents.label')), data: { remote: true }, class: 'btn btn-primary bi bi-check' %>
          <button type="button" class="btn btn-secondary" id="formCloseBtn" data-bs-dismiss="modal"><%= t('shared.cancel') %></button>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/documents/create.js.erb
<% if @document.errors.present? %>
  $('#modal .modal-flash-messages').html("<%= escape_javascript render partial: 'shared/flash_messages', flash: flash %>");
<% else %>
  $('#flash_messages').html("<%= escape_javascript render partial: 'shared/flash_messages', flash: flash %>");
  $('#modal').modal('hide');
  $.get(window.location.origin + window.location.pathname + "/documents.js");
  $('#nav_documents').tab('show');
<% end %>

app/views/documents/destroy.js.erb
<% if @document.errors.blank? %>
  $.get(window.location.origin + window.location.pathname + "/documents.js");
  $('#nav_documents').tab('show');
<% end %>
$('#flash_messages').html("<%= escape_javascript render partial: 'shared/flash_messages', flash: flash %>");

app/views/documents/index.js.erb
$('#nav_documents').html("<%= escape_javascript render 'documents', documents: @documents, attachable: @attachable %>")

app/views/documents/new.js.erb
$('#modal').html("<%= escape_javascript render('form', document: @document, attachable: @attachable) %>");
$('#modal .modal-header').html("<h1><%= t('shared.create_new_resource', resource_label: t('documents.label')) %></h1>");
$('#modal').modal('show');