config/routes.rb
Rails.application.routes.draw do
  root to: 'dashboard#home'
  get '/list_companies', to: 'list_companies#list_companies'
  post '/list_companies', to: 'list_companies#list_companies'
  get '/history', to: 'issues#history'
  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_server'
  get '/401', to: 'errors#access_denied'
  get '/422', to: 'errors#unprocessable'

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations', confirmations: 'users/confirmations' }, path: 'accounts', path_names: { sign_up: 'new' }

  constraints(subdomain: /^(?!www\Z)(\w+)/) do
    get '/companies/search', to: 'companies#search'

    resources :projects do
      member do
        get 'backlog'
        get 'active_sprint'
      end
      resources :sprints
      resources :projects_users
      resources :issues
    end
    resources :sprints do
      resources :issues
      resources :documents, except: %i[edit update]
      member do
        get 'start_sprint_info'
        patch 'start_sprint'
        get 'complete_sprint_info'
        post 'complete_sprint'
        get 'report'
      end
    end

    resources :issues do
      resources :time_logs
      resources :documents, except: %i[edit update]
      collection do
        post 'add_issues_to_sprint'
        get 'fetch_resource_issues', as: 'fetch_resource'
        get 'add_remove_watcher'
      end
    end
    resources :issues do
      resources :time_logs
    end
    resources :dashboard

    resources :users do
    end

    get '/history', to: 'issues#history'
    resources :reports, only: :index do
      collection do
        get 'sprint'
        get 'issues'
      end
    end
  end
end

app/models/project.rb
class Project < ApplicationRecord

  include DateValidations
  include TimeProgressions
  searchkick word_middle: %i[name], filterable: %i[company_id]

  before_destroy :check_for_sprints, :check_for_issues

  belongs_to :company
  belongs_to :manager, class_name: 'User'
  belongs_to :creator, class_name: 'User'
  belongs_to :active_sprint, class_name: 'Sprint', optional: true

  has_many :issues
  has_many :sprints
  has_many :projects_users, dependent: :destroy
  has_many :users, through: :projects_users, dependent: :destroy

  sequenceid :company, :projects

  validates :name, :manager, :creator, presence: true
  validates :name, length: { maximum: 100, minimum: 4 }
  validate_datetime :start_date
  validate_datetime :end_date
  validate_dates :start_date, :end_date

  def total_time_spent
    if issues.any?
      issues.sum(:estimated_time)
    end
  end

  def total_logged_time
    TimeLog.joins(:issue).sum(:logged_time)
  end

  def total_time_spent
    total_time = 0
    if issues.any?
      total_time = TimeLog.joins(:issue).sum(:logged_time)
    end
  end

  def total_estimated_time
    total_time = 0
    if issues.any?
      total_time = issues.sum(:estimated_time)
    end
  end

  def self.project_lead_fetch_sprints
    @current_company.projects.where(manager: current_user)
  end

  def sprints_and_issues
    sprints = self.sprints.includes(:issues).where(status: Sprint::STATUS[:PLANNING]).order(:start_date, :created_at)
    issues = self.issues.where(sprint: nil)
    [sprints, issues]
  end

  def pending_sprints
    sprints.includes(:issues).where(status: Sprint::STATUS[:PLANNING]).order(:start_date, :created_at)
  end

  def backlog_issues
    issues.where(sprint_id: nil)
  end

  def fetch_project_issues
    if active_sprint.present?
      active_sprint.issues
    end
  end

  def fetch_sprint_issues
    if active_sprint.present?
      active_sprint.issues
    end
  end

  private

  def check_for_sprints
    return unless sprints.exists?

    errors.add(:base, I18n.t('projects.deletion_error'))
    throw :abort
  end

  def check_for_issues
    return unless issues.exists?

    errors.add(:base, I18n.t('issues.deletion_error'))
    throw :abort
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  load_and_authorize_resource find_by: :sequence_num, through: :current_company
  load_resource :issues, find_by: :sequence_num, through: :project
  before_action :add_breadcrumbs, only: [:new, :edit, :index, :show]
  # GET /projects
  def index
    @projects = @projects.includes(:issues).paginate(page: params[:page])
    respond_to do |format|
      format.html
    end
  end

  # GET /projects/new
  def new
    add_breadcrumb t('shared.new'), new_project_path
    respond_to do |format|
      format.html
    end
  end

  # POST /projects/
  def create
    @project.creator = current_user
    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: t('shared.success.create', resource_label: t('projects.project_label')) }
      else
        format.html do
          flash.now[:error] = @project.errors.full_messages
          render :new
        end
      end
    end
  end

  # GET /projects/:sequence_num/edit
  def edit
    add_breadcrumb t('shared.edit'), edit_project_path
    respond_to do |format|
      format.html
    end
  end

  # POST /projects/:sequence_num/edit
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: t('shared.success.update', resource_label: t('projects.project_label')) }
      else
        format.html do
          flash.now[:error] = @project.errors.full_messages
          render :edit
        end
      end
    end
  end

  # GET /projects/:sequence_num
  def show
    add_breadcrumb @project.name, project_path
    respond_to do |format|
      format.js
      format.html
    end
  end

  # DELETE /projects/:sequence_num
  def destroy
    respond_to do |format|
      if @project.destroy
        format.html { redirect_to projects_url, alert: t('shared.success.delete', resource_label: t('projects.project_label')) }
      else
        format.html do
          flash.now[:error] = @project.errors.full_messages
          render :show
        end
      end
    end
  end

  # GET /projects/:sequence_num/backlog
  def backlog
    @sprints = @project.pending_sprints
    @issues = @project.backlog_issues
    @projects = [@project]
    @users = @current_company.users
    @issues = FilteringParams.new(@issues, params).apply_filters
    respond_to do |format|
      format.js
    end
  end

  # GET /projects/:sequence_num/active_sprint
  def active_sprint
    @active_sprint = @project.active_sprint
    unless @active_sprint.nil?
      @issues = @active_sprint.categorized_issues
    end
    respond_to do |format|
      format.js
    end
  end

  private

  def project_params
    params.require(:project).permit(:name, :start_date, :end_date, :manager_id)
  end

  def add_breadcrumbs
    add_breadcrumb t('projects.project_label').pluralize, projects_path
  end
end

app/views/projects/_active_sprint.html.erb
<div class="container">
  <div class="mt-3 d-flex justify-content-between">
    <h3>
      <%= link_to sprint.name, sprint %>
    </h3>
    <%= link_to(t('sprints.complete'), complete_sprint_info_sprint_path(sprint), data: { remote: true, method: :get }, class: "btn btn-outline-primary") %>
  </div>
  <div class="row my-3">
    <div class="col card dashboard-card-border shadow-lg mx-1">
      <h6 class="card-header d-flex justify-content-between">
        <span><%= t('shared.to_do').capitalize %></span>
        <span class="badge rounded-pill bg-primary"><%= issues_to_do.size %></span>
      </h6>
      <div class="card-body">
        <% issues_to_do.each do |issue| %>
          <div class="card shadow-lg my-3">
            <div class="card-body">
              <div class="card-title">
                <%= link_to issue.title, issue %>
              </div>
              <div class="card-subtitle badge bg-<%= get_priority_color(issue.priority) %> mb-2 ">
                <%= issue.priority %>
              </div>
              <div class="card-subtitle badge bg-<%= get_category_color(issue.category) %> mb-2 ">
                <%= issue.category %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col card dashboard-card-border shadow-lg mx-1">
      <h6 class="card-header d-flex justify-content-between">
        <span><%= t('shared.in_progress').capitalize %></span>
        <span class="badge rounded-pill bg-primary"><%= issues_in_progress.size %></span>
      </h6>
      <div class="card-body">
        <% issues_in_progress.each do |issue| %>
          <div class="card shadow-lg my-3">
            <div class="card-body">
              <div class="card-title">
                <%= link_to issue.title, issue %>
              </div>
              <div class="card-subtitle badge bg-<%= get_priority_color(issue.priority) %> mb-2 ">
                <%= issue.priority %>
              </div>
              <div class="card-subtitle badge bg-<%= get_category_color(issue.category) %> mb-2 ">
                <%= issue.category %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col card dashboard-card-border shadow-lg mx-1">
      <h6 class="card-header d-flex justify-content-between">
        <span><%= t('shared.resolved').capitalize %></span>
        <span class="badge rounded-pill bg-primary"><%= issues_resolved.size %></span>
      </h6>
      <div class="card-body">
        <% issues_resolved.each do |issue| %>
          <div class="card shadow-lg my-3">
            <div class="card-body">
              <div class="card-title">
                <%= link_to issue.title, issue %>
              </div>
              <div class="card-subtitle badge bg-<%= get_priority_color(issue.priority) %> mb-2 ">
                <%= issue.priority %>
              </div>
              <div class="card-subtitle badge bg-<%= get_category_color(issue.category) %> mb-2 ">
                <%= issue.category %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col card dashboard-card-border shadow-lg mx-1">
      <h6 class="card-header d-flex justify-content-between">
        <span><%= t('shared.closed').capitalize %></span>
        <span class="badge rounded-pill bg-primary"><%= issues_closed.size %></span>
      </h6>
      <div class="card-body">
        <% issues_closed.each do |issue| %>
          <div class="card shadow-lg my-3">
            <div class="card-body">
              <div class="card-title">
                <%= link_to issue.title, issue %>
              </div>
              <div class="card-subtitle badge bg-<%= get_priority_color(issue.priority) %> mb-2 ">
                <%= issue.priority %>
              </div>
              <div class="card-subtitle badge bg-<%= get_category_color(issue.category) %> mb-2 ">
                <%= issue.category %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/projects/_backlog.html.erb
<div class="container mt-3">
  <div class="mb-3 d-flex justify-content-between">
    <h5><%= t('issues.issue_label').pluralize %></h5>
    <%= link_to "", "#", class: 'bi bi-caret-down-fill', id: "issue_dropdown" %>
  </div>
  <div id="issues_table" class="collapse">
    <% if issues.blank? %>
      <div class="d-flex justify-content-center">
        <% render partial: 'shared/no_resource_present', locals: { record: t('issues.issue_label') } %>
      </div>
    <% else %>
      <%= submit_tag t('issues.add_issues'), data: { remote: true }, class: "btn btn-primary add-issues mb-3", disabled: true %>
      <div class="card dashboard-card-border">
        <div class="card-body">
          <table class="table table-hover border-primary text-center my-3" id="issues-datatable" data-source="<%= issues_path(format: :json) %>">
            <thead class="text-light bg-primary">
              <tr>
                <th><%= check_box_tag "check all" %></th>
                <th><%= t('issues.title') %></th>
                <th><%= t('issues.status') %></th>
                <th><%= t('issues.priority') %></th>
                <th><%= t('issues.category') %></th>
              </tr>
            </thead>
            <tbody>
              <% issues.each do |issue| %>
              <tr id="issue_<%= issue.id %>">
                <td><%= check_box_tag "issue_#{issue.id}", issue.id, false, class:"issue-check-box" %></td>
                <td><%= link_to issue.title, issue_path(issue.sequence_num) %></td>
                <td><%= issue.status.camelize %></td>
                <td><%= issue.priority.camelize %></td>
                <td><%= issue.category.camelize %></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/projects/_backlog_issues.html.erb
<% if issues.blank? %>
  <div class="d-flex justify-content-center">
    <%= render partial: 'shared/no_resource_present', locals: { record: t('issues.issue_label') } %>
  </div>
<% else %>
  <%= submit_tag t('issues.add_issues'), data: { remote: true }, class: "btn btn-primary add-issues mb-3", disabled: true %>
  <div class="card dashboard-card-border shadow-lg">
    <div class="card-body">
      <table class="table table-hover border-primary text-center my-3 js-datatable" id="issues-datatable" data-source="<%= issues_path(format: :json) %>">
        <thead class="text-light bg-primary">
          <tr>
            <th><%= check_box_tag "check all" %></th>
            <th><%= t('issues.title') %></th>
            <th><%= t('issues.status') %></th>
            <th><%= t('issues.priority') %></th>
            <th><%= t('issues.category') %></th>
          </tr>
        </thead>
        <tbody>
          <% issues.each do |issue| %>
            <tr id="issue_<%= issue.id %>">
              <td><%= check_box_tag "issue_#{issue.id}", issue.id, false, class:"issue-check-box" %></td>
              <td><%= link_to issue.title, issue_path(issue.sequence_num) %></td>
              <td><span class="badge rounded-pill bg-<%= get_status_color(issue.status) %>"><%= issue.status.camelize %></span></td>
              <td><span class="badge rounded-pill bg-<%= get_priority_color(issue.priority) %>"><%= issue.priority.camelize %></span></td>
              <td><span class="badge rounded-pill bg-<%= get_category_color(issue.category) %>"><%= issue.category.camelize %></span></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
<% end %>

app/views/projects/_backlog_sprints.html.erb
<div class="container mt-3">
  <a class="mb-3 d-flex justify-content-between" href="#" id="sprint_dropdown">
    <h5><%= t('sprints.label').pluralize %></h5>
    <span id="sprint_dopdown_icon" class="bi bi-caret-down-fill"></span>
  </a>
  <div id="sprints_table" class="collapse">
    <table class="table table-borderless my-3" id="inactive-sprints">
      <tbody>
        <% sprints.each_with_index do |sprint, index| %>
          <tr id="sprint_<%=sprint.sequence_num%>">
            <td>
              <div class="card shadow-lg dashboard-card-border">
                <div class="card-body d-flex justify-content-between">
                  <div>
                    <b><%= link_to sprint.name, sprint %></b>
                    <small class="fs-6 fw-lighter" id="no_of_issues">
                      <%= pluralize(sprint.issues.size, t('issues.issue_label')) %>
                    </small>
                  </div>
                  <div>
                    <% if project.active_sprint.nil? %>
                      <%= link_to t('sprints.start'), start_sprint_info_sprint_path(sprint), data: { remote: true, method: :get }, class: "btn btn-outline-primary"+( index == 0? "" : " disabled"), style: ( index == 0 ? {} : { "pointer-events:" => :none} ) %>
                    <% end %>
                  </div>
                </div>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/projects/_details.html.erb
<div class="container pt-3">
  <div class="row bm-3">
    <div class="col-3 ">
      <p><strong><%= t('shared.creator') %>:</strong></p>
    </div>
    <div class="col-3">
      <p><%= link_to @project.creator.name, @project.creator %></p>
    </div>
    <div class="col-3 ">
      <p><strong><%= t('projects.manager') %>:</strong></p>
    </div>
    <div class="col-3">
      <p><%= link_to @project.manager.name, @project.manager %></p>
    </div>
  </div>
  <div class="row bm-3">
    <div class="col-3 ">
      <p><strong><%= start_date_label(project.start_date) %>:</strong></p>
    </div>
    <div class="col-3">
      <p><%= project.start_date&.to_formatted_s(:long) %></p>
    </div>
    <div class="col-3 ">
      <p><strong><%= end_date_label(project.end_date) %>:</strong></p>
    </div>
    <div class="col-3">
      <p><%= project.end_date&.to_formatted_s(:long) %></p>
    </div>
  </div>
</div>

app/views/projects/_form.html.erb
  <%= form_with model: project do |form| %>
  <div class="row g-3 align-items-center mb-3">
    <div class="col-12 col-sm-4 col-md-4 col-lg-2 asterick">
      <%= form.label t('shared.name'), min: 4, class: 'col-form-label col-form-label-md control-label' %>
    </div>
    <div class="col-12 col-sm-6 col-md-6 col-lg-6 asterick">
      <%= form.text_field :name, required: true, class: 'form-control form-control-md control-label' %>
    </div>
  </div>
  <div class="row g-3 align-items-center mb-3">
    <div class="col-12 col-sm-4 col-md-4 col-lg-2">
      <%= form.label t('shared.start_date'), class: 'col-form-label col-form-label-md control-label' %>
    </div>
    <div class="col-12 col-sm-8 col-md-6 col-lg-6">
      <%= form.date_field :start_date, class: 'form-control form-control-md js-flatpickr-datetime' %>
    </div>
  </div>
  <div class="row g-3 align-items-center mb-3">
    <div class="col-12 col-sm-4 col-md-4 col-lg-2">
      <%= form.label t('shared.end_date'), class: 'col-form-label col-form-label-md control-label' %>
    </div>
    <div class="col-12 col-sm-8 col-md-6 col-lg-6">
      <%= form.date_field :end_date, class: 'form-control form-control-md js-flatpickr-datetime' %>
    </div>
  </div>
  <% if can? :create, @project %>
    <div class="row g-3 align-items-center mb-3">
      <div class="col-12 col-sm-4 col-md-4 col-lg-2 asterick">
        <%= form.label t('shared.manager'), class: 'col-form-label col-form-label-md control-label' %>
      </div>
      <div class="col-12 col-sm-8 col-md-6 col-lg-6 ">
        <%= form.select :manager_id, @current_company.users.map{ |user| [user.email, user.id] }, { required: true }, { class: "form-select form-select-md js-select-field-single" } %>
      </div>
    </div>
  <% end %>
  <div class="row d-flex justify-content-center">
    <div class="col-2 ">
      <%= form.submit class: 'btn btn-primary w-100 bi bi-check' %>
    </div>
    <div class="col-2 ">
      <%= link_to t('shared.back'), projects_path, class: 'btn btn-secondary w-100' %>
    </div>
  </div>
<% end %>

app/views/projects/_show.html.erb
<div class="container mt-3">
  <div class="row bm-3 d-flex">
    <div class="col-8">
      <h1><%= project.name %></h1>
    </div>
    <div class="col-2 justify-content-end">
      <%= link_to t('shared.edit'), edit_project_path(project), class: "btn btn-primary w-100 bi bi-pencil" %>
    </div>
    <% if can? :delete, Project %>
      <div class="col-2 justify-content-end">
        <%= link_to t('shared.delete'), project_path(project),
                method: :delete,
                data: { confirm: t('shared.confirmation') }, class: "btn btn-danger w-100 bi bi-trash" %>
      </div>
    <% end %>
  </div>
  <hr/>
</div>
<div class="container">
  <div class="row bm-3">
    <div class="col-3 ">
      <p><strong><%=t('projects.creator')%>:</strong></p>
    </div>
    <div class="col-3">
      <p><%= project.owner.name %></p>
    </div>
    <div class="col-3 ">
      <p><strong><%=t('projects.manager')%>:</strong></p>
    </div>
    <div class="col-3">
      <p><%= project.manager.name %></p>
    </div>
  </div>
  <div class="row bm-3">
    <div class="col-3 ">
      <p><strong><%= project_start_date_label %>:</strong></p>
    </div>
    <div class="col-3">
      <p><%= project.start_date %></p>
    </div>
    <div class="col-3 ">
      <p><strong><%= project_end_date_label %>:</strong></p>
    </div>
    <div class="col-3">
      <p><%= project.end_date %></p>
    </div>
  </div>
  <hr/>
</div>

app/views/projects/active_sprint.js.erb
<% if @active_sprint.nil? %>
  $('#nav-active-sprint').html("<p class='d-flex justify-content-center my-3'><%= escape_javascript t('projects.active_sprint_absent') %> <%= escape_javascript(link_to t('projects.backlog'), backlog_project_path, data: { remote: true }, id: "backlog_redirect") %></p>");
  $('#backlog_redirect').on('click', function(event){
    event.preventDefault();
    $('#nav-backlog-tab').tab('show');
  });
<% else %>
  $('#nav-active-sprint').html("<%= escape_javascript render('active_sprint', sprint: @active_sprint, issues_to_do: @issues[:to_do], issues_in_progress: @issues[:in_progress], issues_resolved: @issues[:resolved], issues_closed: @issues[:closed] )%>")
<% end %>

app/views/projects/backlog.js.erb
<% if @sprints.any? %>
  $('#nav-backlog #backlog_sprints').html("<%= escape_javascript (render "backlog_sprints", project: @project, sprints: @sprints) %>")
  $('#nav-backlog #backlog_issues #backlog_issues_content').html("<%= escape_javascript (render "backlog_issues", project: @project, sprints: @sprints, issues: @issues) %>")

  <% if (Issue::FILTER.values & params.keys).empty?  %>
    $('#nav-backlog #backlog_issues #filter').html("<%= escape_javascript (render(:partial => 'issues/filter',  :locals=>{issues: @issues, users: @users, projects: @projects, form_action: "backlog"})) %>")
  <% end %>


  $('.add-issues').on('click', function() {
    $('#modal').html('<%= escape_javascript (render "sprints/select_sprint", sprints: @sprints) %>');
    $('#modal').modal('show');
  });

  $('body').on('click', '#check_all', function() {
    if ($('#check_all').prop("checked")) {
      $(".issue-check-box").each(function() {
        $(this).prop("checked", true);
        $(this).trigger('change');
      })
    } else {
      $(".issue-check-box").each(function() {
        $(this).prop("checked", false);
        $(this).trigger('change');
      })
    }
  });

  $('body').on('change', ".issue-check-box", function() {
    let checked = false;
    $(".issue-check-box").each(function() {
      if ($(this).prop("checked")) {
        checked = true;
      }
    })
    checked ? $(".add-issues").prop("disabled", false) : $(".add-issues").prop("disabled", true)
  });

  $('body').on('click', '.add-issues-to-sprint', function() {
    let issue_ids = [];
    $('.issue-check-box').each(function() {
      if ($(this).prop("checked")) {
        issue_ids.push($(this).val());
      }
    });
    $('.issue_ids').val(issue_ids);
    $(".add-issues").prop("disabled", true);
  });
<% else %>
  $('#nav-backlog').html("<%= escape_javascript (render partial: 'shared/no_resource_present', locals: { record: t('sprints.label') }) %>");
<% end %>
$('.js-select-field').select2({
  width: 200
});
$(document).on('select2:select',".js-select-field", function (e){
  var select_container_id = e.params.data["id"];
  $('.btn-apply-filter').show();
  $('.btn-remove-filter').hide();
  $("#"+select_container_id).addClass('show');
  $( ".js-"+select_container_id+"-field").prop( "disabled", false );
});

$('body').on('select2:open', '.js-select-field', () => {
  document.querySelector('.select2-search__field').focus();
});
$('.js-remove-filter').on('click', function(e){
  e.preventDefault();
  var parent = this.parentNode.parentNode.id;
  var id ="#"+parent
  var className = ".js-"+parent+"-field"
  $(id).hide();
  $(className).prop( "disabled", true );
  var data = $('form').serialize();
   if (data.match(/&/g).length < 2)
  {
    $('.btn-apply-filter').hide();
    $('.btn-remove-filter').show();
  }
});

app/views/projects/edit.html.erb
<%= render partial: 'shared/breadcrumb' %>
<div class="container">
  <h1><%= t('shared.edit_resource', resource_label: t('projects.project_label')) %></h1>
  <hr />
</div>
<div class="container">
  <%= render 'form', project: @project, users: @users %>
</div>

app/views/projects/show.html.erb
<div class="container">
  <div class="row my-3 d-flex justify-content-between">
    <%= render partial: 'shared/breadcrumb' %>
    <div class="col-8">
      <h1><%= @project.name %></h1>
    </div>
    <% if can? :edit, @project %>
      <div class="col-2">
        <%= link_to t('shared.edit'), edit_project_path(@project), class: "btn btn-primary w-100 bi bi-pencil" %>
      </div>
    <% end %>
    <% if can? :destroy, @project %>
      <div class="col-2">
        <%= link_to t('shared.delete'), project_path(@project),
      method: :delete,
      data: { confirm: t('shared.confirmation') }, class: "btn btn-danger w-100 bi bi-trash" %>
      </div>
    <% end %>
  </div>
</div>
<div class="container">
  <nav>
    <div class="nav nav-tabs" id="nav-tab" role="tablist">
      <%= link_to t('shared.details'), @project, class: 'nav-link active', id: "nav-projects-tab", data: {bs_toggle: "tab", bs_target: "#nav-projects"},  type: "button", role: 'tab', aria_controls: "nav-projects", aria_selected: true %>
      <%= link_to t('sprints.label').pluralize(), [@project, :sprints], remote: true, class: 'nav-link', id: "nav-sprints-tab", data: {bs_toggle: "tab", bs_target: "#nav-sprints"}, type: "button", role: 'tab', aria_controls: "nav-sprints", aria_selected: false %>
      <%= link_to t('issues.issue_label').pluralize(), project_issues_path(@project), remote: true, class: 'nav-link', id: "nav-issues-tab", data: {bs_toggle: "tab", bs_target: "#nav-issues"}, type: "button", role: 'tab', aria_controls: "nav-issues", aria_selected: false %>
      <%= link_to t('users.label').pluralize(), [@project, :projects_users], remote: true, class: 'nav-link', id: "nav-users-tab", data: {bs_toggle: "tab", bs_target: "#nav-users"}, type: "button", role: 'tab', aria_controls: "nav-users", aria_selected: false %>
      <%= link_to t('projects.backlog').pluralize(), [:backlog, @project], remote: true, class: 'nav-link', id: "nav-backlog-tab", data: {bs_toggle: "tab", bs_target: "#nav-backlog"}, type: "button", role: 'tab', aria_controls: "nav-backlog", aria_selected: false %>
      <%= link_to t('projects.active_sprint'), [:active_sprint, @project], remote: true, class: 'nav-link', id: "nav-active-sprint-tab", data: {bs_toggle: "tab", bs_target: "#nav-active-sprint"}, type: "button", role: 'tab', aria_controls: "nav-active-sprint", aria_selected: false %>
    </div>
  </nav>
  <div class="tab-content" id="tab-tabContent">
    <div class="tab-pane fade show active" id="nav-projects" role="tabpanel" aria-labelledby="nav-projects-tab">
      <%= render 'details', project: @project %>
    </div>
    <div class="tab-pane fade" id="nav-issues" role="tabpanel" aria-labelledby="nav-issues-tab">
      <div class="container">
        <div id="header" ></div>
        <% if (Issue::FILTER.keys & params.keys).empty? %>
          <div id="filter"></div>
        <% end %>
        <div id="issues-table"></div>
      </div>
    </div>
    <div class="tab-pane fade" id="nav-sprints" role="tabpanel" aria-labelledby="nav-sprints-tab"></div>
    <div class="tab-pane fade" id="nav-users" role="tabpanel" aria-labelledby="nav-users-tab"></div>
    <div class="tab-pane fade" id="nav-backlog" role="tabpanel" aria-labelledby="nav-backlog-tab">
      <div id="backlog_sprints"></div>
      <div id="backlog_issues">
        <div class="container mt-3">
          <a class="mb-3 d-flex justify-content-between" id="issue_dropdown" href="#">
            <h5><%= t('issues.issue_label').pluralize %></h5>
            <span id="issue_dopdown_icon" class="bi bi-caret-down-fill"></span>
          </a>
          <div id="issues_table" class="collapse">
            <div id="filter"></div>
            <div id="backlog_issues_content"></div>
          </div>
        </div>
      </div>
    </div>
    <div class="tab-pane fade" id="nav-active-sprint" role="tabpanel" aria-labelledby="nav-active-sprint-tab"></div>
  </div>
</div>

app/views/projects/show.js.erb
$('#nav-projects').html("<%= escape_javascript render('show', @project) %>");